version: 0.0
os: linux
files:
   - source: /
     destination: /home/deploy/myapp
permissions:
   - object: /home/deploy/myapp
     pattern: "**"
     owner: ubuntu
     group: ubuntu
     mode: 755
     type:
       - file
hooks:
   BeforeInstall:
    - location: scripts/startnginx.sh
      runas: root
   AfterInstall:
    - location: scripts/restartnginx.sh
      runas: root
